### ISSUE TITLE
Is tmux necessary? Does surreal support Windows?

### ISSUE THREAD

**Issue by forhonourlx** [SurrealAI/surreal#1]
Surreal framework does leave me a deep impression.
 Is tmux a necessary requirement? 
Does surreal support Windows?
Looking forward to see surreal growing.
Thank you.

**Comment by jirenz** [comment]
* Tmux is not strictly required as you can go straight to setup on a kubernetes cluster. However it is recommended since being able to run code locally helps faster iteration.
* We only support Mac and Linux.
