### ISSUE TITLE
Support for external agents?

### ISSUE THREAD

**Issue by ahundt** [SurrealAI/surreal#11]
I'd like to run the algorithms with an external agent where surreal doesn't have control of time (like a real robot). See [Interefacing with External Agents in Berkeley's Ray library](https://ray.readthedocs.io/en/latest/rllib-env.html?highlight=external#interfacing-with-external-agents) for details and an example. Is this already designed into surreal or is the concept not yet implemented?

Note: I've also created a couple of related issues in https://github.com/StanfordVL/robosuite/issues sorry if one of these are in the wrong place.

**Comment by LinxiFan** [comment]
The SURREAL agent has to be "internal" now, but we will put external-interfacing on our todo list. Thanks!
