### ISSUE TITLE
robosuite:SawyerLift doesn't run

### ISSUE THREAD

**Issue by kapsl** [SurrealAI/surreal#12]
When I try to run the robosuite exeriments i get messages that basically all observations are skipped:

Mujoco: skipping observation key: joint_pos
Mujoco: skipping observation key: joint_vel
...

and finally I get an exception in torch/nn/modules/rnn.py line 52: sizes must be non-negative

How is it possible to get the robosuite environment running? Thanks a lot!

**Comment by LinxiFan** [comment]
https://github.com/SurrealAI/surreal/pull/14
This should address the problem. Thanks!
