### ISSUE TITLE
Running on local machines

### ISSUE THREAD

**Issue by kapsl** [SurrealAI/surreal#13]
We also think about using surreal for controlling several real robots. You said that this could be achieved by setting up a kubernetes cluster locally, but you are also working on some different solution. What would you think is the best way to achieve this in the next few months?

**Comment by LinxiFan** [comment]
Is it multi-node mode that you wish to have? Currently we only have support for the cloud, but we are working on an SSH backend to provide non-cloud multi-node training. If you are in a hurry, please set up a local Kubernetes cluster with this tutorial: https://kubernetes.io/docs/setup/

**Comment by kapsl** [comment]
We eventually plan to run around 3 robots and a few simulations in parallel. I guess this will be to heave to run on one machine...

**Comment by LinxiFan** [comment]
If you can run on one machine, that'd be the most ideal situation.
