### ISSUE TITLE
How to connect to a custom LAN Kubernetes cluster?

### ISSUE THREAD

**Issue by forhonourlx** [SurrealAI/surreal#15]
Hi Surreal Team,
I have setup a LAN Kubernetes cluster like following:
NAME      STATUS   ROLES    AGE     VERSION
gtx1080   Ready    master   13m     v1.12.3
rtx2080   Ready    <none>   6m38s   v1.12.3

Then I got stuck in this step  "surreal_kube_gke.md -> Kube on your own -> 4.When creating the cluster using cloudwise ..."
What are the detailed steps when I am connecting to a custom LAN Kubernetes cluster?
Is cloudwise still needed and how to use it?

Thank you indeed if you could show some instructions.

**Comment by forhonourlx** [comment]
Hi Jiren,
I appreciate your kindness.

Yes, you are correct. The following is the return of "kubectl get nodes".
NAME STATUS ROLES AGE VERSION
gtx1080 Ready master 13m v1.12.3
rtx2080 Ready <none> 6m38s v1.12.3

Thank you for your help.

**Comment by jirenz** [comment]
I need `kubectl describe node gtx1080` and `kubectl describe node rtx2080`. It will tell me what resources are there on your cluster so I can figure out a way to put components on it.

**Comment by forhonourlx** [comment]
Understood.
For I am outing, I would provide describe a few hours later.
Would you please have a look later as your convenient?
Thank you.

**Comment by jirenz** [comment]
Sure. I will need some time as well since LAN can be slightly different.

**Comment by LinxiFan** [comment]
We currently only have explicit support for commercial clouds like GCE. Support for custom Kube cluster is on our to-do list. Thanks for your patience!
