### ISSUE TITLE
where's the command "surreal-default-config"?

### ISSUE THREAD

**Issue by GrazyThinking** [SurrealAI/surreal#2]
When I followed the instruction in "surreal_tmux.md", I can't find the command "surreal-default-config".

![image](https://user-images.githubusercontent.com/18043631/47842938-0c6f0e00-ddf9-11e8-8d36-85239573bf05.png)

How should I do to get this command? 
Thanks!

**Comment by jirenz** [comment]
`surreal-default-config` is installed with surreal. Have you done `pip install surreal`?

**Comment by GrazyThinking** [comment]
@jirenz OK, Thanks!
