### ISSUE TITLE
"subproc" is not a valid cluster backend

### ISSUE THREAD

**Issue by krishpop** [SurrealAI/surreal#27]
Currently, it seems that the subproc is not part of the BACKEND_REGISTRY in symphony, which makes it difficult to attempt running experiments locally.

Are the versions out of sync or something?

**Comment by LinxiFan** [comment]
Have you updated your `symphony` installation? You can pull from https://github.com/surrealai/symphony and run `pip install -e symphony/` outside the folder.
We will update the package on PyPI soon.

**Comment by krishpop** [comment]
Thank you! That worked.

**Comment by LinxiFan** [comment]
I just updated `symphony` to `v0.10` on PyPI. You should be able to run `pip install --upgrade symphony` now. Thanks for the issue!
