### ISSUE TITLE
How to use PPOLauncher?

### ISSUE THREAD

**Issue by forhonourlx** [SurrealAI/surreal#4]
When I was running:
simon@simon-GTX1080:~/Desktop/surreal/surreal/main$ python ppo_configs.py [-h] --env 'pong' --num-agents 16 [--num-gpus 1] [--agent-num-gpus 1] --experiment-folder './test'
usage: ppo_configs.py [-h] component_name
ppo_configs.py: error: unrecognized arguments: --env pong --num-agents 16 [--num-gpus 1] [--agent-num-gpus 1] --experiment-folder ./test

Could somebody give a helping hand? Thank you.

**Comment by zihualiu** [comment]
Hi, `ppo_config.py` only contains a component of the Surreal framework. We provide a centralized scheduler to help you navigate creating experiments and managing them. Please see the following links for installation and running locally/on the cloud

Installation + local: https://github.com/SurrealAI/surreal/blob/master/docs/installation.md
On the cloud: https://github.com/SurrealAI/surreal/blob/master/docs/surreal_kube_gke.md

**Comment by forhonourlx** [comment]
Hi Liu Zihua,

Unfortunately after the following cmd, I still got stucked in the very first steps.
Could you kindly give some help? Thank you.

sudo snap install kubectl --classic
surreal-default-config
sudo gedit ~/.surreal.yml
...
prefix_experiment_with_username: False
kube_metadata_folder: ~/Desktop/surreal/_kube_metadata/
kube_results_folder: ~/Desktop/surreal/_kube_results/
...
surreal-kube create cpu-experiment my-first-experiment

Traceback (most recent call last):
  File "/home/simon/anaconda3/bin/surreal-kube", line 11, in <module>
    load_entry_point('Surreal==0.1.1', 'console_scripts', 'surreal-kube')()
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/kube/surreal_kube.py", line 556, in main
    KurrealParser().main()
  File "/home/simon/anaconda3/lib/python3.6/site-packages/symphony/commandline/commandline_interface.py", line 549, in main
    args.func(args)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/kube/surreal_kube.py", line 196, in action_create
    raise KeyError('Cannot find setting {}'.format(setting_name))
KeyError: 'Cannot find setting cpu-experiment'

**Comment by jirenz** [comment]
This seems to be an error in the documentation due to updates in the config defaults. The tutorial is now updated.
Please use `cpu-gym` in place of `cpu-experiment`. 

Are you running a Kubernetes cluster? From the setting in the config it looks like you are trying to run things locally? Please use [tmux mode](https://github.com/SurrealAI/surreal/blob/master/docs/installation.md) if you want to run things.

Under the hood, the `surreal-kube cpu-gym` commandline is looking for 
```
# ~/.surreal.yml
creation_settings:
  cpu-gym:
    ...
```
We have updated to naming to improve readability of the config but the name in the tutorial is outdated. Thank you for bringing this up!

**Comment by forhonourlx** [comment]
Hi Jiren and Linxi,
Thank you for your help.
tmux mode runs successfully locally.

And one more question need your help:
my hardware env is 4 different machines in LAN each with a GPU,  how to apply surreal to set up a distributed or cooperated RL experiment gathering all machines?

Thanks again.

**Comment by LinxiFan** [comment]
Thanks for bringing this up. It's always been on our to-do list. We plan to roll out a new backend that supports LAN-multinode. Currently, you can always set up a custom Kubernetes cluster yourself on the LAN machines: https://kubernetes.io/docs/setup/scratch/
