### ISSUE TITLE
It seems no experiment running after 'surreal-tmux create ...'

### ISSUE THREAD

**Issue by forhonourlx** [SurrealAI/surreal#5]
Hi Surreal Team,

After the following cmds:
export CUDA_VISIBLE_DEVICES=0
surreal-tmux create --algorithm ppo --env 'gym:HalfCheetah-v2' --num_agents 4 single_gpu_test_2
it returns:
experiment name string has been fixed: single_gpu_test_2 -> single-gpu-test-2
Writing experiment output to /home/simon/Desktop/surreal/_tmux/single-gpu-test-2
Putting agents, evals and learner on GPU 0
Creating new Experiment "<your_username>-single-gpu-test-2"
 --> Created process learner
 --> Created process replay
 --> Created process ps
 --> Created process tensorboard
 --> Created process tensorplex
 --> Created process loggerplex
 --> Created process agent-0
 --> Created process agent-1
 --> Created process agent-2
 --> Created process agent-3

See in: http://localhost:6006
All tf.variable_scope shows a plain  scalar of 0

nvidia-smi shows low loads:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.73       Driver Version: 410.73       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   48C    P2    38W / 250W |   1557MiB /  8116MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1120      G   /usr/lib/xorg/Xorg                           726MiB |
|    0      1347      G   /usr/bin/gnome-shell                         446MiB |
|    0      1968      G   /opt/teamviewer/tv_bin/TeamViewer             13MiB |
|    0      3723      G   ...-token=87E9286EF38E96D5B6113738A1BF619F   279MiB |
|    0     23765      G   ...quest-channel-token=9428749015434365802    87MiB |
+-----------------------------------------------------------------------------+

I don't know whether experiment is running.
Could you please kindly see what is the wrong?
Or what should I do in advance?

Thank you.

**Comment by jirenz** [comment]
The experiment seems to be launched properly. Since `nvidia-smi` does not show anything I suspect that something crashed after starting. You can use the tmux command line to monitor the experiment: `surreal-tux p` shows all running processes and `surreal-tux logs agent-0`, `surreal-tux logs learner` shows the logs of the corresponding components. We can help figure out what is wrong if you can post these logs.

FWI `use surreal-tmux delete` to delete an experiment that you no longer wants.

**Comment by forhonourlx** [comment]
Hi Jiren,
We have some time diff, and thanks for taking a look:

simon@simon-GTX1080:~$ surreal-tmux create --algorithm ppo --env 'gym:HalfCheetah-v2' --num_agents 4 single_gpu_test_3
experiment name string has been fixed: single_gpu_test_3 -> single-gpu-test-3
Writing experiment output to /home/simon/Desktop/surreal/_tmux/single-gpu-test-3
Putting agents, evals and learner on GPU 0
Creating new Experiment "<your_username>-single-gpu-test-3"
 --> Created process learner
 --> Created process replay
 --> Created process ps
 --> Created process tensorboard
 --> Created process tensorplex
 --> Created process loggerplex
 --> Created process agent-0
 --> Created process agent-1
 --> Created process agent-2
 --> Created process agent-3
 --> Created process eval-0

simon@simon-GTX1080:~$ surreal-tmux p
Group  Name         status  
       learner      live    
       replay       live    
       ps           live    
       tensorboard  live    
       tensorplex   live    
       loggerplex   live    
       agent-0      live    
       agent-1      live    
       agent-2      live    
       agent-3      live    
       eval-0       live 

simon@simon-GTX1080:~$ surreal-tmux logs learner
simon@simon-GTX1080:~$  export CUDA_VISIBLE_DEVICES=0
simon@simon-GTX1080:~$  export SYMPH_TENSORBOARD_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_TENSORBOARD_PORT=6006
simon@simon-GTX1080:~$  export SYMPH_TENSORBOARD_ADDR=127.0.0.1:6006
simon@simon-GTX1080:~$  export SYMPH_PARAMETER_PUBLISH_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PARAMETER_PUBLISH_PORT=7000
simon@simon-GTX1080:~$  export SYMPH_PARAMETER_PUBLISH_ADDR=127.0.0.1:7000
simon@simon-GTX1080:~$  export SYMPH_PREFETCH_QUEUE_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PREFETCH_QUEUE_PORT=7001
simon@simon-GTX1080:~$  export SYMPH_PREFETCH_QUEUE_ADDR=127.0.0.1:7001
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_FRONTEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_FRONTEND_PORT=7002
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_FRONTEND_ADDR=127.0.0.1:7002
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_FRONTEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_FRONTEND_PORT=7003
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_FRONTEND_ADDR=127.0.0.1:7003
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_BACKEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_BACKEND_PORT=7004
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_BACKEND_ADDR=127.0.0.1:7004
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_BACKEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_BACKEND_PORT=7005
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_BACKEND_ADDR=127.0.0.1:7005
simon@simon-GTX1080:~$  export SYMPH_PS_FRONTEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PS_FRONTEND_PORT=7006
simon@simon-GTX1080:~$  export SYMPH_PS_FRONTEND_ADDR=127.0.0.1:7006
simon@simon-GTX1080:~$  export SYMPH_PS_BACKEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PS_BACKEND_PORT=7007
simon@simon-GTX1080:~$  export SYMPH_PS_BACKEND_ADDR=127.0.0.1:7007
simon@simon-GTX1080:~$  export SYMPH_TENSORPLEX_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_TENSORPLEX_PORT=7008
simon@simon-GTX1080:~$  export SYMPH_TENSORPLEX_ADDR=127.0.0.1:7008
simon@simon-GTX1080:~$  export SYMPH_LOGGERPLEX_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_LOGGERPLEX_PORT=7009
simon@simon-GTX1080:~$  export SYMPH_LOGGERPLEX_ADDR=127.0.0.1:7009
simon@simon-GTX1080:~$  source activate base
 surreal-ppo learner -- --num-agents 4 --experiment-folder /home/simon/Desktop/surreal/_tmux/single-gpu-test-3 --env gym:HalfCheetah-v2
(base) simon@simon-GTX1080:~$  surreal-ppo learner -- --num-agents 4 --experiment-folder /home/simon/Desktop/surreal/_tmux/single-gpu-test-3 --env gym:HalfCheetah-v2
07:37:36 INFO> Using GPU: cuda:all
Fatal Python error: Segmentation fault
Thread 0x00007f9fea0e5700 (most recent call first):
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorplex/zmq_queue.py", line 108 in _run_batch
  File "/home/simon/anaconda3/lib/python3.6/threading.py", line 864 in run
  File "/home/simon/anaconda3/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/simon/anaconda3/lib/python3.6/threading.py", line 884 in _bootstrap
Thread 0x00007f9feb8e8700 (most recent call first):
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorplex/zmq_queue.py", line 108 in _run_batch
  File "/home/simon/anaconda3/lib/python3.6/threading.py", line 864 in run
  File "/home/simon/anaconda3/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/simon/anaconda3/lib/python3.6/threading.py", line 884 in _bootstrap
Current thread 0x00007fa05ff48740 (most recent call first):
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 162 in _lazy_init
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 158 in set_default_tensor_type
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torchx/device.py", line 161 in set_default_device_dtype
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torchx/device.py", line 245 in device_scope
  File "/home/simon/anaconda3/lib/python3.6/contextlib.py", line 81 in __enter__
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/learner/ppo.py", line 130 in __init__
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/utils/common.py", line 271 in __call__
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/launch/launcher.py", line 329 in setup_learner
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/launch/launcher.py", line 314 in run_learner
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/launch/launcher.py", line 157 in launch
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/launch/launcher.py", line 56 in main
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/main/ppo_configs.py", line 231 in main
  File "/home/simon/anaconda3/bin/surreal-ppo", line 11 in <module>
段错误 (核心已转储)
(base) simon@simon-GTX1080:~$

simon@simon-GTX1080:~$ surreal-tmux logs agent-0
simon@simon-GTX1080:~$  export CUDA_VISIBLE_DEVICES=0
simon@simon-GTX1080:~$  export SYMPH_TENSORBOARD_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_TENSORBOARD_PORT=6006
simon@simon-GTX1080:~$  export SYMPH_TENSORBOARD_ADDR=127.0.0.1:6006
simon@simon-GTX1080:~$  export SYMPH_PARAMETER_PUBLISH_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PARAMETER_PUBLISH_PORT=7000
simon@simon-GTX1080:~$  export SYMPH_PARAMETER_PUBLISH_ADDR=127.0.0.1:7000
simon@simon-GTX1080:~$  export SYMPH_PREFETCH_QUEUE_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PREFETCH_QUEUE_PORT=7001
simon@simon-GTX1080:~$  export SYMPH_PREFETCH_QUEUE_ADDR=127.0.0.1:7001
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_FRONTEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_FRONTEND_PORT=7002
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_FRONTEND_ADDR=127.0.0.1:7002
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_FRONTEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_FRONTEND_PORT=7003
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_FRONTEND_ADDR=127.0.0.1:7003
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_BACKEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_BACKEND_PORT=7004
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_BACKEND_ADDR=127.0.0.1:7004
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_BACKEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_BACKEND_PORT=7005
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_BACKEND_ADDR=127.0.0.1:7005
simon@simon-GTX1080:~$  export SYMPH_PS_FRONTEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PS_FRONTEND_PORT=7006
simon@simon-GTX1080:~$  export SYMPH_PS_FRONTEND_ADDR=127.0.0.1:7006
simon@simon-GTX1080:~$  export SYMPH_PS_BACKEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PS_BACKEND_PORT=7007
simon@simon-GTX1080:~$  export SYMPH_PS_BACKEND_ADDR=127.0.0.1:7007
simon@simon-GTX1080:~$  export SYMPH_TENSORPLEX_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_TENSORPLEX_PORT=7008
simon@simon-GTX1080:~$  export SYMPH_TENSORPLEX_ADDR=127.0.0.1:7008
simon@simon-GTX1080:~$  export SYMPH_LOGGERPLEX_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_LOGGERPLEX_PORT=7009
simon@simon-GTX1080:~$  export SYMPH_LOGGERPLEX_ADDR=127.0.0.1:7009
simon@simon-GTX1080:~$  source activate base
 surreal-ppo agent-0 -- --num-agents 4 --experiment-folder /home/simon/Desktop/surreal/_tmux/single-gpu-test-3 --env gym:HalfCheetah-v2
(base) simon@simon-GTX1080:~$  surreal-ppo agent-0 -- --num-agents 4 --experiment-folder /home/simon/Desktop/surreal/_tmux/single-gpu-test-3 --env gym:HalfCheetah-v2
07:37:39 INFO> PPO agent is using GPU
Traceback (most recent call last):
  File "/home/simon/anaconda3/bin/surreal-ppo", line 11, in <module>
    load_entry_point('Surreal==0.1.1', 'console_scripts', 'surreal-ppo')()
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/main/ppo_configs.py", line 231, in main
    PPOLauncher().main()
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/launch/launcher.py", line 56, in main
    self.launch(args.component_name)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/launch/launcher.py", line 145, in launch
    self.run_agent(agent_id=component_id)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/launch/launcher.py", line 189, in run_agent
    agent = self.setup_agent(agent_id)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/launch/launcher.py", line 214, in setup_agent
    agent_mode=agent_mode,
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/utils/common.py", line 271, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/Surreal-0.1.1-py3.6.egg/surreal/agent/ppo_agent.py", line 71, in __init__
    self.log.info('cudnn version: {}'.format(torch.backends.cudnn.version()))
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 78, in version
    if _libcudnn() is None:
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 71, in _libcudnn
    'but linked against {}'.format(compile_version, __cudnn_version))
RuntimeError: cuDNN version incompatibility: PyTorch was compiled against 7301 but linked against 7201

**Comment by forhonourlx** [comment]
Hi Linxi,
Thanks a lot. It is caused by cudnn version.
Here 'surreal-tmux create ...' runs successfully.
Please close this issue.

simon@simon-GTX1080:~$ surreal-tmux create --algorithm ppo --env 'gym:HalfCheetah-v2' --num_agents 4 single_gpu_test_4
experiment name string has been fixed: single_gpu_test_4 -> single-gpu-test-4
Writing experiment output to /home/simon/Desktop/surreal/_tmux/single-gpu-test-4
Putting agents, evals and learner on GPU 0
Creating new Experiment "<your_username>-single-gpu-test-4"
 --> Created process learner
 --> Created process replay
 --> Created process ps
 --> Created process tensorboard
 --> Created process tensorplex
 --> Created process loggerplex
 --> Created process agent-0
 --> Created process agent-1
 --> Created process agent-2
 --> Created process agent-3
 --> Created process eval-0
simon@simon-GTX1080:~$ surreal-tmux p
Group  Name         status  
       learner      live    
       replay       live    
       ps           live    
       tensorboard  live    
       tensorplex   live    
       loggerplex   live    
       agent-0      live    
       agent-1      live    
       agent-2      live    
       agent-3      live    
       eval-0       live    
simon@simon-GTX1080:~$ surreal-tmux logs learner
simon@simon-GTX1080:~$  export CUDA_VISIBLE_DEVICES=0
simon@simon-GTX1080:~$  export SYMPH_TENSORBOARD_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_TENSORBOARD_PORT=6006
simon@simon-GTX1080:~$  export SYMPH_TENSORBOARD_ADDR=127.0.0.1:6006
simon@simon-GTX1080:~$  export SYMPH_PARAMETER_PUBLISH_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PARAMETER_PUBLISH_PORT=7000
simon@simon-GTX1080:~$  export SYMPH_PARAMETER_PUBLISH_ADDR=127.0.0.1:7000
simon@simon-GTX1080:~$  export SYMPH_PREFETCH_QUEUE_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PREFETCH_QUEUE_PORT=7001
simon@simon-GTX1080:~$  export SYMPH_PREFETCH_QUEUE_ADDR=127.0.0.1:7001
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_FRONTEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_FRONTEND_PORT=7002
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_FRONTEND_ADDR=127.0.0.1:7002
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_FRONTEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_FRONTEND_PORT=7003
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_FRONTEND_ADDR=127.0.0.1:7003
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_BACKEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_BACKEND_PORT=7004
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_BACKEND_ADDR=127.0.0.1:7004
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_BACKEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_BACKEND_PORT=7005
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_BACKEND_ADDR=127.0.0.1:7005
simon@simon-GTX1080:~$  export SYMPH_PS_FRONTEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PS_FRONTEND_PORT=7006
simon@simon-GTX1080:~$  export SYMPH_PS_FRONTEND_ADDR=127.0.0.1:7006
simon@simon-GTX1080:~$  export SYMPH_PS_BACKEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PS_BACKEND_PORT=7007
simon@simon-GTX1080:~$  export SYMPH_PS_BACKEND_ADDR=127.0.0.1:7007
simon@simon-GTX1080:~$  export SYMPH_TENSORPLEX_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_TENSORPLEX_PORT=7008
simon@simon-GTX1080:~$  export SYMPH_TENSORPLEX_ADDR=127.0.0.1:7008
simon@simon-GTX1080:~$  export SYMPH_LOGGERPLEX_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_LOGGERPLEX_PORT=7009
simon@simon-GTX1080:~$  export SYMPH_LOGGERPLEX_ADDR=127.0.0.1:7009
simon@simon-GTX1080:~$  source activate base
 surreal-ppo learner -- --num-agents 4 --experiment-folder /home/simon/Desktop/surreal/_tmux/single-gpu-test-4 --env gym:HalfCheetah-v2
(base) simon@simon-GTX1080:~$  surreal-ppo learner -- --num-agents 4 --experiment-folder /home/simon/Desktop/surreal/_tmux/single-gpu-test-4 --env gym:HalfCheetah-v2
01:36:55 INFO> Using GPU: cuda:all
11-12 01:37:24 INFO> [PUB] binding to tcp://*:7000
11-12 01:37:24 INFO> [REP] binding to tcp://127.0.0.1:7001
11-12 01:37:24 INFO> [REQ] connecting to tcp://127.0.0.1:7003
11-12 01:37:24 INFO> [REQ] connecting to tcp://127.0.0.1:7003
11-12 01:37:24 INFO> [REQ] connecting to tcp://127.0.0.1:7003
11-12 01:37:24 INFO> [REQ] connecting to tcp://127.0.0.1:7001
11-12 01:37:24 INFO> [REQ] connecting to tcp://127.0.0.1:7001
11-12 01:37:24 INFO> [REQ] connecting to tcp://127.0.0.1:7003
11-12 01:37:24 INFO> [REQ] connecting to tcp://127.0.0.1:7001
11-12 01:37:24 INFO> [REQ] connecting to tcp://127.0.0.1:7001
simon@simon-GTX1080:~$ surreal-tmux logs agent-0
simon@simon-GTX1080:~$  export CUDA_VISIBLE_DEVICES=0
simon@simon-GTX1080:~$  export SYMPH_TENSORBOARD_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_TENSORBOARD_PORT=6006
simon@simon-GTX1080:~$  export SYMPH_TENSORBOARD_ADDR=127.0.0.1:6006
simon@simon-GTX1080:~$  export SYMPH_PARAMETER_PUBLISH_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PARAMETER_PUBLISH_PORT=7000
simon@simon-GTX1080:~$  export SYMPH_PARAMETER_PUBLISH_ADDR=127.0.0.1:7000
simon@simon-GTX1080:~$  export SYMPH_PREFETCH_QUEUE_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PREFETCH_QUEUE_PORT=7001
simon@simon-GTX1080:~$  export SYMPH_PREFETCH_QUEUE_ADDR=127.0.0.1:7001
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_FRONTEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_FRONTEND_PORT=7002
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_FRONTEND_ADDR=127.0.0.1:7002
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_FRONTEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_FRONTEND_PORT=7003
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_FRONTEND_ADDR=127.0.0.1:7003
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_BACKEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_BACKEND_PORT=7004
simon@simon-GTX1080:~$  export SYMPH_COLLECTOR_BACKEND_ADDR=127.0.0.1:7004
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_BACKEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_BACKEND_PORT=7005
simon@simon-GTX1080:~$  export SYMPH_SAMPLER_BACKEND_ADDR=127.0.0.1:7005
simon@simon-GTX1080:~$  export SYMPH_PS_FRONTEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PS_FRONTEND_PORT=7006
simon@simon-GTX1080:~$  export SYMPH_PS_FRONTEND_ADDR=127.0.0.1:7006
simon@simon-GTX1080:~$  export SYMPH_PS_BACKEND_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_PS_BACKEND_PORT=7007
simon@simon-GTX1080:~$  export SYMPH_PS_BACKEND_ADDR=127.0.0.1:7007
simon@simon-GTX1080:~$  export SYMPH_TENSORPLEX_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_TENSORPLEX_PORT=7008
simon@simon-GTX1080:~$  export SYMPH_TENSORPLEX_ADDR=127.0.0.1:7008
simon@simon-GTX1080:~$  export SYMPH_LOGGERPLEX_HOST=127.0.0.1
simon@simon-GTX1080:~$  export SYMPH_LOGGERPLEX_PORT=7009
simon@simon-GTX1080:~$  export SYMPH_LOGGERPLEX_ADDR=127.0.0.1:7009
simon@simon-GTX1080:~$  source activate base
 surreal-ppo agent-0 -- --num-agents 4 --experiment-folder /home/simon/Desktop/surreal/_tmux/single-gpu-test-4 --env gym:HalfCheetah-v2
(base) simon@simon-GTX1080:~$  surreal-ppo agent-0 -- --num-agents 4 --experiment-folder /home/simon/Desktop/surreal/_tmux/single-gpu-test-4 --env gym:HalfCheetah-v2
01:36:59 INFO> PPO agent is using GPU
01:36:59 INFO> cudnn version: 7201
11-12 01:37:22 INFO> [REQ] connecting to tcp://127.0.0.1:7006
11-12 01:37:22 INFO> [REQ] connecting to tcp://127.0.0.1:7002
Parameter client came back alive
