### ISSUE TITLE
How to understand tensorboard indicators and how to add custom indicators?

### ISSUE THREAD

**Issue by forhonourlx** [SurrealAI/surreal#7]
Hi Surreal Team,
I found following indicators:
agent/step_per_s/, agent.reward/

replay.core/exp_in_per_s/, replay.core/exp_out_per_s/, replay.core/insert_time_s/, replay.core/num_exps/, replay.core/requests_per_s/, replay.core/sample_time_s/, replay.core/serialize_time_s/, replay.core/total_collected_exps/, replay.core/total_sample_requests/, replay.core/total_sampled_exps/

Which one does stand for Average Return?
Which indicators should be focused on?
And how to add custom indicators to monitor?

Thank you.

**Comment by jirenz** [comment]
`agent.reward/` is the average return. This should be the metric to focus on.

We use tensorplex to add indicators to monitor. See
[learner](https://github.com/SurrealAI/surreal/blob/368f7c24ded6ee841a76f025345008a61717906e/surreal/learner/ppo.py#L611)
[agent performance statistics](https://github.com/SurrealAI/surreal/blob/368f7c24ded6ee841a76f025345008a61717906e/surreal/agent/base.py#L167)
[agent reward statistics](https://github.com/SurrealAI/surreal/blob/368f7c24ded6ee841a76f025345008a61717906e/surreal/env/monitor.py#L157)
