### ISSUE TITLE
Gym environment wrong

### ISSUE THREAD

**Issue by kapsl** [SurrealAI/surreal#8]
Hi,
I installed surreal after your instructions. But when trying to start the half-cheeta-v2 environement it says that that version is not there and only v1 is available. Is there something special I have to do about the gym module to get the right one? Also when I start with cheeta-v1 I get some error which is eventually due to version conflicts (but I have the newest one regarding to pip).

Another issue is, that when starting locally with the robosuite environment - my pc dies, due to very hard harddrive operations. Is there something I can do to lower the load?

**Comment by LinxiFan** [comment]
I think you have to update your gym installation. The latest gym has only v2 but not v1.
