### ISSUE TITLE
Getting error AttributeError: 'float' object has no attribute 'item'

### ISSUE THREAD

**Issue by kapsl** [SurrealAI/surreal#9]
manuel@sdi-learning:~$  export SYMPH_SAMPLER_FRONTEND_HOST=127.0.0.1
manuel@sdi-learning:~$  export SYMPH_PREFETCH_QUEUE_HOST=127.0.0.1
manuel@sdi-learning:~$  export SYMPH_COLLECTOR_BACKEND_HOST=127.0.0.1
manuel@sdi-learning:~$  export SYMPH_PREFETCH_QUEUE_ADDR=127.0.0.1:7006
manuel@sdi-learning:~$  export SYMPH_LOGGERPLEX_ADDR=127.0.0.1:7007
manuel@sdi-learning:~$  export SYMPH_PARAMETER_PUBLISH_HOST=127.0.0.1
manuel@sdi-learning:~$  export SYMPH_TENSORBOARD_ADDR=127.0.0.1:6006
manuel@sdi-learning:~$  export SYMPH_COLLECTOR_BACKEND_ADDR=127.0.0.1:7002
manuel@sdi-learning:~$  export SYMPH_PS_FRONTEND_ADDR=127.0.0.1:7005
manuel@sdi-learning:~$  export SYMPH_COLLECTOR_FRONTEND_PORT=7001
manuel@sdi-learning:~$  export SYMPH_LOGGERPLEX_PORT=7007
manuel@sdi-learning:~$  export SYMPH_PS_BACKEND_HOST=127.0.0.1
manuel@sdi-learning:~$  export SYMPH_COLLECTOR_FRONTEND_HOST=127.0.0.1
manuel@sdi-learning:~$  export SYMPH_SAMPLER_FRONTEND_ADDR=127.0.0.1:7008
manuel@sdi-learning:~$  export SYMPH_COLLECTOR_FRONTEND_ADDR=127.0.0.1:7001
manuel@sdi-learning:~$  export SYMPH_SAMPLER_FRONTEND_PORT=7008
manuel@sdi-learning:~$  export SYMPH_PS_FRONTEND_HOST=127.0.0.1
manuel@sdi-learning:~$  export SYMPH_TENSORPLEX_HOST=127.0.0.1
manuel@sdi-learning:~$  export SYMPH_TENSORBOARD_HOST=127.0.0.1
manuel@sdi-learning:~$  export SYMPH_PS_BACKEND_ADDR=127.0.0.1:7003
manuel@sdi-learning:~$  export SYMPH_TENSORBOARD_PORT=6006
manuel@sdi-learning:~$  export SYMPH_SAMPLER_BACKEND_HOST=127.0.0.1
manuel@sdi-learning:~$  export SYMPH_PREFETCH_QUEUE_PORT=7006
manuel@sdi-learning:~$  export SYMPH_TENSORPLEX_ADDR=127.0.0.1:7004
manuel@sdi-learning:~$  export SYMPH_PARAMETER_PUBLISH_PORT=7000
manuel@sdi-learning:~$  export SYMPH_TENSORPLEX_PORT=7004
manuel@sdi-learning:~$  export SYMPH_LOGGERPLEX_HOST=127.0.0.1
manuel@sdi-learning:~$  export SYMPH_PS_FRONTEND_PORT=7005
manuel@sdi-learning:~$  export SYMPH_PS_BACKEND_PORT=7003
manuel@sdi-learning:~$  export SYMPH_SAMPLER_BACKEND_ADDR=127.0.0.1:7009
manuel@sdi-learning:~$  export SYMPH_PARAMETER_PUBLISH_ADDR=127.0.0.1:7000
manuel@sdi-learning:~$  export SYMPH_COLLECTOR_BACKEND_PORT=7002
manuel@sdi-learning:~$  export SYMPH_SAMPLER_BACKEND_PORT=7009
manuel@sdi-learning:~$  source /home/manuel/anaconda3/bin/activate sac
 surreal-ppo learner -- --num-agents 2 --experiment-folder /home/manuel/surreal/tmux/ppo-test --env robosuite:SawyerLift
(sac) manuel@sdi-learning:~$  surreal-ppo learner -- --num-agents 2 --experiment-folder /home/manuel/surreal/tmux/ppo-test --env robosuite:SawyerLift
Found 1 GPUs for rendering. Using device 0.
Mujoco: skipping observation key: joint_pos
Mujoco: skipping observation key: joint_vel
Mujoco: skipping observation key: gripper_qpos
Mujoco: skipping observation key: gripper_qvel
Mujoco: skipping observation key: eef_pos
Mujoco: skipping observation key: eef_quat
Mujoco: skipping observation key: robot-state
Mujoco: skipping observation key: object-state
15:08:46 INFO> Using GPU: cuda:all
11-15 15:14:17 INFO> [PUB] binding to tcp://*:7000
11-15 15:14:44 INFO> [REP] binding to tcp://127.0.0.1:7006
11-15 15:14:59 INFO> [REQ] connecting to tcp://127.0.0.1:7008
11-15 15:15:00 INFO> [REQ] connecting to tcp://127.0.0.1:7008
11-15 15:15:00 INFO> [REQ] connecting to tcp://127.0.0.1:7006
11-15 15:15:02 INFO> [REQ] connecting to tcp://127.0.0.1:7006
11-15 15:15:08 INFO> [REQ] connecting to tcp://127.0.0.1:7008
11-15 15:15:08 INFO> [REQ] connecting to tcp://127.0.0.1:7006
11-15 15:15:08 INFO> [REQ] connecting to tcp://127.0.0.1:7008
11-15 15:15:08 INFO> [REQ] connecting to tcp://127.0.0.1:7006
Traceback (most recent call last):
  File "/home/manuel/anaconda3/envs/sac/bin/surreal-ppo", line 11, in <module>
    sys.exit(main())
  File "/home/manuel/anaconda3/envs/sac/lib/python3.5/site-packages/surreal/main/ppo_configs.py", line 231, in main
    PPOLauncher().main()
  File "/home/manuel/anaconda3/envs/sac/lib/python3.5/site-packages/surreal/launch/launcher.py", line 56, in main
    self.launch(args.component_name)
  File "/home/manuel/anaconda3/envs/sac/lib/python3.5/site-packages/surreal/launch/launcher.py", line 157, in launch
    self.run_learner()
  File "/home/manuel/anaconda3/envs/sac/lib/python3.5/site-packages/surreal/launch/launcher.py", line 315, in run_learner
    learner.main()
  File "/home/manuel/anaconda3/envs/sac/lib/python3.5/site-packages/surreal/learner/base.py", line 357, in main
    self.main_loop()
  File "/home/manuel/anaconda3/envs/sac/lib/python3.5/site-packages/surreal/learner/base.py", line 373, in main_loop
    self.learn(data)
  File "/home/manuel/anaconda3/envs/sac/lib/python3.5/site-packages/surreal/learner/ppo.py", line 604, in learn
    batch.dones,
  File "/home/manuel/anaconda3/envs/sac/lib/python3.5/site-packages/surreal/learner/ppo.py", line 552, in _optimize
    ref_pol)
  File "/home/manuel/anaconda3/envs/sac/lib/python3.5/site-packages/surreal/learner/ppo.py", line 307, in _adapt_update
    self.actor_gradient_clip_value).item()
AttributeError: 'float' object has no attribute 'item'

**Comment by kapsl** [comment]
Found this: Can try the workaround on monday. 

Still is there a trick for testing independent parts of surreal? E.g. a way to just start the learner and see if there's a bug. Elseway I always have to wait 10min after starting ;-( - and still it freezes my system

**Comment by jirenz** [comment]
We find it easier to run local integration test. Check [these files](https://github.com/SurrealAI/surreal/tree/master/test).

**Comment by LinxiFan** [comment]
We are aware of this issue and will post a patch soon
